// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEdhcWCZgqyzENuqNuyXpG5MO0QOrShk',
    appId: '1:1076192054275:web:a47e8414d5f1318e451236',
    messagingSenderId: '1076192054275',
    projectId: 'to-do-list-fbf6d',
    authDomain: 'to-do-list-fbf6d.firebaseapp.com',
    storageBucket: 'to-do-list-fbf6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5V6x9vVhBOXjQWw7JZzi3ld3o4GASrbQ',
    appId: '1:1076192054275:android:cf84e12eda3b74bf451236',
    messagingSenderId: '1076192054275',
    projectId: 'to-do-list-fbf6d',
    storageBucket: 'to-do-list-fbf6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQPsZbVev-qxu-EPsPstxi7DurVFuzWQ',
    appId: '1:1076192054275:ios:be9f60aa52be34cc451236',
    messagingSenderId: '1076192054275',
    projectId: 'to-do-list-fbf6d',
    storageBucket: 'to-do-list-fbf6d.appspot.com',
    iosClientId: '1076192054275-5bjnq2npvud7s1tkh2refo20p6bple0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQPsZbVev-qxu-EPsPstxi7DurVFuzWQ',
    appId: '1:1076192054275:ios:be9f60aa52be34cc451236',
    messagingSenderId: '1076192054275',
    projectId: 'to-do-list-fbf6d',
    storageBucket: 'to-do-list-fbf6d.appspot.com',
    iosClientId: '1076192054275-5bjnq2npvud7s1tkh2refo20p6bple0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );
}
